# Netlify configuration
[build]
  publish = "."
  
# Form notifications
[[plugins]]
  package = "@netlify/plugin-form-submissions"

# Email notification settings for form submissions
[functions]
  # Forms will automatically send notifications to the site owner's email
  
# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
